name: deploy
run-name: blog deploy 🚀

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      message:
        description: 'message to commit'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'

      - name: Build Web
        run: hugo --minify

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXTERNAL_REPOSITORY: zjcrender/zjcrender.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
          full_commit_message: ${{ inputs.message }}
          commit_message: ${{ github.event.head_commit.message }}
          
